include: package:very_good_analysis/analysis_options.yaml

analyzer:
  
  # Statik Kod Analiz Aracından hariç tutulacak dosyalar #
  exclude:
    ### [Eklediklerim] ###
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - lib/app/generated/**.dart
    - lib/app/generated/**include: package:very_good_analysis/analysis_options.yaml

  # Aşağıdakileri Error/Hata olarak nitele #
  errors:
   ### [Eklediklerim] ###
    invalid_assignment: warning
    dead_code: info
    todo: ignore
    unawaited_futures: warning
    unused_import: warning
    invalid_annotation_target: ignore

# Dart dili için katı kuralları etkinleştir #
  language:
    
linter:
  rules:
    ### [Eklediklerim - True] ###,
    # DecoratedBox'ı tercih et
    use_decorated_box: true
    # tek bir ifade döndüren fonksiyonlar için süslü parantez {} yerine => (ok) kullan
    # prefer_expression_function_bodies: true
    # lib/ dizini içindekiler için Relative import'u tercih et#
    prefer_relative_imports: true
    
    ### [Değiştirdiklerim - False] ###
    # Proje içi importlarda paket bazlı import kullanımını zorunlu tutma
    always_use_package_imports: false
    # TODO yorum stilin zorunlu tutma
    flutter_style_todos: false
    # Kod satır uzunluğu 80 karakteri geçebilir
    lines_longer_than_80_chars: false
    # Public üye ve API dokümantasyonu için /// şeklindeki dokümantasyon yorumlarını zorunlu tutma.
    public_member_api_docs: false
    # pubspec.yaml dosyasındaki bağımlılıkların alfabetik olarak sıralanmasını zorunlu tutma.
    sort_pub_dependencies: false